version: '2.2'

services:
  nodeposts:
    image: nodeposts
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
       - /Users/$user/mongodb:/data/db
    ports:
      - "27017:27017"